<a href="https://colab.research.google.com/github/JSEFERINO/C_Datos/blob/main/8_C_Datos_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Curso Introductorio a la Ciencia de Datos por Julio Hurtado Márquez**
## **Parte I**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

#**34. Creando un dataFrame usando arrays**
##**a. Construyamos una matriz que contenga el día y fecha de cumpleaños de mi familia**

In [ ]:
# Creando un array
data = np.array([[2,6], [9,25], [3,21], [7,21], [12,10], [9,21]])
data

array([[ 2,  6],
       [ 9, 25],
       [ 3, 21],
       [ 7, 21],
       [12, 10],
       [ 9, 21]])

## **b. Creamos el DataFrame**

In [ ]:
#Creando un data Frame
pd.DataFrame(data)

    0   1
0   2   6
1   9  25
2   3  21
3   7  21
4  12  10
5   9  21

## **c. Las Filas son los membros de la Familia y el mes de cumpleaños**

In [ ]:
#Creando un data Frame
fh = pd.DataFrame(data, index = ["Julio", "Marelis", "Aris", "Dayana", "Cofy", "Chiqui"], columns= ["Mes","Dia"])
fh

         Mes  Dia
Julio      2    6
Marelis    9   25
Aris       3   21
Dayana     7   21
Cofy      12   10
Chiqui     9   21

#**35. Creando un DataFrame en Python usando lista**

## **a. Creamos una lista con cumpleaños**

In [ ]:
# **a. Creamos una lista con cumpleaños**
cumpleaños3 = [[2,6], [9,25], [3,21], [7,21], [12,10], [9,21]]
cumpleaños3

[[2, 6], [9, 25], [3, 21], [7, 21], [12, 10], [9, 21]]

## **b. Creando un data Frame de la misma forma que en el caso 1**

In [ ]:
## **Creando un data Frame**
fh2 = pd.DataFrame(cumpleaños3, index = ["Julio", "Marelis", "Aris", "Dayana", "Cofy", "Chiqui"], columns= ["Mes","Dia"])
fh2

         Mes  Dia
Julio      2    6
Marelis    9   25
Aris       3   21
Dayana     7   21
Cofy      12   10
Chiqui     9   21

## **c. Cree un DataFrame en Python con los nombres de los departamentos y sus capitaes**

In [ ]:
# **c. Creando la lista**
costa = [["Guajira","RioHacha"], ["Magdalena","Santa Marta"], ["Cesár","Valledupar"], ["Atlántico","Barranquilla"], ["Bolivar","Cartagena"], ["Sucre","Sincelejo"], ["Córdova", "Montería"]]

In [ ]:
#Creando un data Frame
C_Caribe = pd.DataFrame(costa, index = ["region1", "region2", "region3", "region4", "region5", "region6", "region7"], columns= ["Dpto","Capital"])
C_Caribe

              Dpto       Capital
region1    Guajira      RioHacha
region2  Magdalena   Santa Marta
region3      Cesár    Valledupar
region4  Atlántico  Barranquilla
region5    Bolivar     Cartagena
region6      Sucre     Sincelejo
region7    Córdova      Montería

#**35. Creando un DataFrame en Python usando diccionarios**

## **a. Creando las listas de las ciudades y dptos**

In [ ]:
ciudad_3 = ['Cartagena', 'Barranquilla', 'Santa Marta', 'Montería', 'Sincelejo', 'Valledupar', 'Riohacha']

In [ ]:
dpto4 = ['Bolívar', 'Atlántico', 'Magdalena', 'Córdoba', 'Sucre', 'Cesar', 'Guajira']

## **b. Creando los diccionarios**

In [ ]:
## **b. Creando los diccionarios**
dic_Dptos = {"Ciudad": ciudad_3, "Departamento":dpto4}

## **c. Creando el DataFrame con los diccionarios**

In [ ]:
## **c. Creando el DataFrame con los diccionarios**
dic_ciudad = pd.DataFrame(dic_Dptos)
dic_ciudad

         Ciudad Departamento
0     Cartagena      Bolívar
1  Barranquilla    Atlántico
2   Santa Marta    Magdalena
3      Montería      Córdoba
4     Sincelejo        Sucre
5    Valledupar        Cesar
6      Riohacha      Guajira

#**36. Crear un DataFrame usando archivos csv**
##**a. Subiendo un archivo csv a Python**

In [ ]:
import cv2 as cv
from google.colab import files
uploaded=files.upload()

Saving DATOS2023py.csv to DATOS2023py (1).csv

## **b. Construimos el DataFrame con el archivo excel**

In [ ]:
# **b. Construimos el DataFrame con el archivo excel**
df_datos2023 = pd.read_csv("/content/DATOS2023py.csv", delimiter=';')
df_datos2023

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,"4,3",COMS,18,SI,55,164,4,350,"4,26",F,II,PTWF
1,ESTADISTICA I,"3,1",COMS,19,SI,65,165,5,328,"4,11",F,I,CYDT
2,ESTADISTICA I,"4,2",DERH,25,NO,56,170,5,285,"3,7",M,I,CYDT
3,ESTADISTICA I,"3,6",DERH,23,SI,65,170,5,280,"4,1",F,II,PCWF
4,ESTADISTICA I,"3,9",PSIC,19,SI,50,169,5,319,4,F,II,CYWF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,ESTADISTICA I,"3,5",PSIC,18,SI,60,163,5,310,"3,9",F,III,PTWF
117,ESTADISTICA I,"3,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PCWF
118,ESTADISTICA I,"2,5",COMS,21,NO,45,172,5,221,"3,7",F,II,CYWF
119,ESTADISTICA I,3,COMS,20,NO,50,160,4,332,"3,5",F,II,CYDT
120,ESTADISTICA I,"3,5",DERH,21,NO,57,160,4,293,"3,5",F,III,PTWF

## **c. Renombramos el archivo para mejorarlo**

In [ ]:
df_datos = df_datos2023
df_datos

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,"4,3",COMS,18,SI,55,164,4,350,"4,26",F,II,PTWF
1,ESTADISTICA I,"3,1",COMS,19,SI,65,165,5,328,"4,11",F,I,CYDT
2,ESTADISTICA I,"4,2",DERH,25,NO,56,170,5,285,"3,7",M,I,CYDT
3,ESTADISTICA I,"3,6",DERH,23,SI,65,170,5,280,"4,1",F,II,PCWF
4,ESTADISTICA I,"3,9",PSIC,19,SI,50,169,5,319,4,F,II,CYWF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,ESTADISTICA I,"3,5",PSIC,18,SI,60,163,5,310,"3,9",F,III,PTWF
117,ESTADISTICA I,"3,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PCWF
118,ESTADISTICA I,"2,5",COMS,21,NO,45,172,5,221,"3,7",F,II,CYWF
119,ESTADISTICA I,3,COMS,20,NO,50,160,4,332,"3,5",F,II,CYDT
120,ESTADISTICA I,"3,5",DERH,21,NO,57,160,4,293,"3,5",F,III,PTWF

## **d. Mostramos las primeras cinco filas del archivo**

In [ ]:
## **d. Mostramos las primeras cinco filas del archivo**
df_datos.head()

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,"4,3",COMS,18,SI,55,164,4,350,"4,26",F,II,PTWF
1,ESTADISTICA I,"3,1",COMS,19,SI,65,165,5,328,"4,11",F,I,CYDT
2,ESTADISTICA I,"4,2",DERH,25,NO,56,170,5,285,"3,7",M,I,CYDT
3,ESTADISTICA I,"3,6",DERH,23,SI,65,170,5,280,"4,1",F,II,PCWF
4,ESTADISTICA I,"3,9",PSIC,19,SI,50,169,5,319,4,F,II,CYWF

## **e. Mostramos las ultimas cinco filas del DataFrame**

In [ ]:
## **e. Mostramos las ultimas cinco filas del DataFrame**
df_datos.tail()

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
116,ESTADISTICA I,"3,5",PSIC,18,SI,60,163,5,310,"3,9",F,III,PTWF
117,ESTADISTICA I,"3,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PCWF
118,ESTADISTICA I,"2,5",COMS,21,NO,45,172,5,221,"3,7",F,II,CYWF
119,ESTADISTICA I,3,COMS,20,NO,50,160,4,332,"3,5",F,II,CYDT
120,ESTADISTICA I,"3,5",DERH,21,NO,57,160,4,293,"3,5",F,III,PTWF

In [ ]:
## **f. Mostramos las primeras 10 filas del DataFrame**
df_datos.head(10)

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,"4,3",COMS,18,SI,55,164,4,350,"4,26",F,II,PTWF
1,ESTADISTICA I,"3,1",COMS,19,SI,65,165,5,328,"4,11",F,I,CYDT
2,ESTADISTICA I,"4,2",DERH,25,NO,56,170,5,285,"3,7",M,I,CYDT
3,ESTADISTICA I,"3,6",DERH,23,SI,65,170,5,280,"4,1",F,II,PCWF
4,ESTADISTICA I,"3,9",PSIC,19,SI,50,169,5,319,4,F,II,CYWF
5,ESTADISTICA I,"1,1",PSIC,19,SI,68,165,4,318,"3,7",M,III,PTWF
6,ESTADISTICA I,"3,5",CIENP,19,SI,86,184,5,345,"4,48",F,II,PTWF
7,ESTADISTICA I,"4,2",CIENP,19,NO,53,163,5,257,"3,7",M,I,PTWF
8,PROBABILIDAD,"4,4",ININ,18,NO,56,158,5,298,"3,8",F,II,PTDT
9,PROBABILIDAD,"4,1",INMT,20,SI,72,179,4,353,"3,9",M,III,PCWF

## **g. Mostramos las últimas 10 filas del DataFrame**

In [ ]:
## **g. Mostramos las últimas 10 filas del DataFrame**
df_datos.tail(10)

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
111,ESTADISTICA I,"1,5",COMS,19,SI,61,156,5,238,"3,5",F,III,PTWF
112,ESTADISTICA I,"3,5",COMS,19,SI,66,110,4,255,40,M,III,PCWF
113,ESTADISTICA I,"4,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PTWF
114,ESTADISTICA I,4,PSIC,18,NO,47,155,5,312,"4,39",F,V,PCWF
115,ESTADISTICA I,"2,5",PSIC,21,SI,70,185,3,356,"3,2",M,II,PCWF
116,ESTADISTICA I,"3,5",PSIC,18,SI,60,163,5,310,"3,9",F,III,PTWF
117,ESTADISTICA I,"3,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PCWF
118,ESTADISTICA I,"2,5",COMS,21,NO,45,172,5,221,"3,7",F,II,CYWF
119,ESTADISTICA I,3,COMS,20,NO,50,160,4,332,"3,5",F,II,CYDT
120,ESTADISTICA I,"3,5",DERH,21,NO,57,160,4,293,"3,5",F,III,PTWF

# **37. Atributos y Métodos del DataFrame**

#**a. Mostrar todas las filas del DataFrame**

In [ ]:
#**a. Mostrar todas las filas del DataFrame**
pd.set_option("display.max_rows",121)
df_datos

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,"4,3",COMS,18,SI,55,164,4,350,"4,26",F,II,PTWF
1,ESTADISTICA I,"3,1",COMS,19,SI,65,165,5,328,"4,11",F,I,CYDT
2,ESTADISTICA I,"4,2",DERH,25,NO,56,170,5,285,"3,7",M,I,CYDT
3,ESTADISTICA I,"3,6",DERH,23,SI,65,170,5,280,"4,1",F,II,PCWF
4,ESTADISTICA I,"3,9",PSIC,19,SI,50,169,5,319,4,F,II,CYWF
5,ESTADISTICA I,"1,1",PSIC,19,SI,68,165,4,318,"3,7",M,III,PTWF
6,ESTADISTICA I,"3,5",CIENP,19,SI,86,184,5,345,"4,48",F,II,PTWF
7,ESTADISTICA I,"4,2",CIENP,19,NO,53,163,5,257,"3,7",M,I,PTWF
8,PROBABILIDAD,"4,4",ININ,18,NO,56,158,5,298,"3,8",F,II,PTDT
9,PROBABILIDAD,"4,1",INMT,20,SI,72,179,4,353,"3,9",M,III,PCWF
10,PROBABILIDAD,"4,8",INNV,18,SI,64,175,4,354,"4,69",M,III,PTWF
11,PROBABILIDAD,"4,5",ININ,17,NO,75,177,4,242,"4,69",F,I,PTDT
12,PROBABILIDAD,"3,9",INQU,19,SI,61,158,4,329,"3,77",F,II,CYDT
13,PROBABILIDAD,"3,3",ININ,17,SI,57,164,5,354,"3,77",M,II,PCWF
14,PROBABILIDAD,4,INMT,18,NO,50,168,5,265,"4,3",M,I,CYDT
15,ESTADISTICA I,"3,8",COMS,20,SI,87,174,5,290,"3,8",M,VI,PTWF
16,ESTADISTICA I,"3,5",COMS,16,SI,54,169,5,325,"4,48",F,II,PTDT
17,ESTADISTICA I,"4,2",DERH,18,SI,80,181,5,273,"3,79",M,IV,TBDT
18,ESTADISTICA I,"3,6",DERH,19,SI,60,182,5,333,4,M,II,PTWF
19,ESTADISTICA I,"4,1",PSIC,18,SI,90,176,5,298,"3,9",M,II,PCWF
20,ESTADISTICA I,"2,5",PSIC,20,SI,50,157,5,310,"3,9",F,II,PCWF
21,ESTADISTICA I,"3,6",CIENP,19,SI,55,156,5,278,"3,86",F,V,PTWF
22,ESTADISTICA I,"4,5",CIENP,18,SI,74,183,5,365,"4,31",M,II,PTWF
23,PROBABILIDAD,4,INST,18,NO,63,183,4,352,"4,02",M,II,PCWF
24,PROBABILIDAD,5,INAM,17,SI,48,158,4,327,"4,22",F,I,PCWF
25,ESTADISTICA I,"3,6",DERH,18,SI,85,179,5,270,"3,82",M,IV,PCWF
26,ESTADISTICA I,4,PSIC,20,SI,60,175,5,214,373,M,I,CYDT
27,ESTADISTICA I,3,PSIC,17,NO,61,155,5,275,37,F,NaN,PCWF
28,ESTADISTICA I,4,CIENP,18,SI,68,185,5,330,"4,01",M,VI,CYDT
29,PROBABILIDAD,"4,5",INMT,17,SI,85,175,5,357,"3,78",M,II,PTWF
30,PROBABILIDAD,"4,3",INBM,17,SI,45,155,5,356,"4,12",F,V,PTWF
31,ESTADISTICA I,"4,5",COMS,17,NO,60,162,4,230,"3,8",F,II,PCWF
32,ESTADISTICA I,3,COMS,18,SI,65,169,5,300,"3,81",M,II,PTWF
33,ESTADISTICA I,"3,5",DERH,21,SI,62,100,5,210,"3,9",F,II,CYWF
34,ESTADISTICA I,"3,2",DERH,17,NO,60,170,5,313,"4,1",M,II,PTDT
35,ESTADISTICA I,"3,6",PSIC,18,SI,56,163,4,292,"4,3",F,III,PTWF
36,ESTADISTICA I,4,PSIC,18,SI,75,190,4,365,"4,03",M,I,PCWF
37,ESTADISTICA I,5,CIENP,19,SI,73,182,5,333,"4,08",M,III,PTWF
38,ESTADISTICA I,"3,8",CIENP,17,NO,73,175,4,342,"4,26",M,I,PCWF
39,PROBABILIDAD,"4,3",INMC,24,NO,90,176,5,240,"3,7",M,II,TBWF
40,PROBABILIDAD,"4,3",INMC,18,SI,47,167,4,311,"4,2",M,III,PCDT
41,ESTADISTICA I,"4,5",COMS,19,SI,50,165,3,316,"3,9",F,II,PTWF
42,ESTADISTICA I,3,COMS,17,SI,70,173,5,355,"4,03",M,III,PTWF
43,ESTADISTICA I,5,DERH,20,SI,63,160,4,273,4,F,I,PTWF
44,PROBABILIDAD,5,INCV,17,NO,37,148,5,230,"3,87",F,I,PTWF
45,PROBABILIDAD,5,FINN,18,SI,58,165,5,273,"4,22",F,II,PTWF
46,PROBABILIDAD,"4,8",ININ,20,SI,73,163,5,263,"3,73",F,II,PTWF
47,PROBABILIDAD,"2,5",INMT,17,SI,64,180,4,358,"3,88",M,II,CYWF
48,PROBABILIDAD,3,INNV,18,NO,80,175,5,289,"3,8",M,II,PTWF
49,PROBABILIDAD,"3,8",INMC,17,NO,70,170,5,269,4,M,I,PCDT
50,ESTADISTICA I,"4,4",COMS,18,SI,60,165,5,380,"4,68",F,IV,CYDT
51,ESTADISTICA I,"2,5",COMS,18,SI,77,180,5,338,"4,1",M,II,PTWF
52,ESTADISTICA I,"4,2",DERH,17,NO,59,169,4,298,"4,01",M,II,CYDT
53,ESTADISTICA I,"3,7",DERH,17,SI,40,164,4,353,"4,33",F,II,PCWF
54,ESTADISTICA I,4,PSIC,18,SI,49,163,5,297,"42,6",F,IV,PTWF
55,ESTADISTICA I,2,PSIC,17,SI,60,164,3,289,"4,1",F,II,PCWF
56,ESTADISTICA I,"3,5",CIENP,17,NO,59,176,4,333,"3,9",M,III,PTWF
57,ESTADISTICA I,"4,2",CIENP,17,SI,62,168,4,298,"4,1",F,I,PTWF
58,PROBABILIDAD,"4,5",INMT,19,SI,74,171,3,370,"4,3",M,II,PTWF
59,PROBABILIDAD,5,INMT,19,SI,64,174,5,352,"4,2",M,III,PCWF
60,PROBABILIDAD,4,INST,22,SI,75,175,5,255,"4,2",M,IV,PTWF
61,PROBABILIDAD,5,FINN,18,NO,51,154,5,368,"4,46",F,II,PTWF
62,ESTADISTICA I,"4,3",COMS,18,SI,37,178,4,270,"3,6",M,II,CYDT
63,ESTADISTICA I,"2,5",COMS,18,NO,75,183,5,328,"4,2",M,I,PTDT
64,ESTADISTICA I,"4,5",DERH,17,SI,45,140,4,341,"4,01",M,I,PTWF
65,PROBABILIDAD,"4,5",INMT,17,SI,60,170,5,341,"4,57",M,I,PTWF
66,PROBABILIDAD,4,INMC,18,NO,60,171,3,364,"4,3",M,III,PCWF
67,PROBABILIDAD,"3,5",INMC,17,SI,90,185,5,300,"3,79",M,III,PTWF
68,PROBABILIDAD,"2,5",ECOM,18,SI,75,170,5,288,"4,01",F,II,PTWF
69,PROBABILIDAD,5,FINN,19,NO,78,175,5,294,"4,6",F,III,PTWF
70,PROBABILIDAD,"4,5",INNV,17,NO,79,174,5,356,"4,4",M,II,PTWF
71,ESTADISTICA I,"4,5",COMS,18,SI,62,169,4,315,"4,1",F,IV,PTWF
72,ESTADISTICA I,"2,5",COMS,18,SI,80,180,5,361,"4,5",M,II,PCWF
73,ESTADISTICA I,"4,2",DERH,19,NO,45,158,4,283,"3,95",F,I,PCWF
74,ESTADISTICA I,"3,7",DERH,18,SI,50,170,4,300,"4,2",M,III,PCWF
75,ESTADISTICA I,4,PSIC,18,SI,59,165,5,310,"4,4",F,IV,PCDT
76,ESTADISTICA I,2,PSIC,18,SI,65,166,5,250,"4,3",M,II,PTWF
77,ESTADISTICA I,"3,5",CIENP,20,SI,73,192,3,356,"3,83",M,III,PCWF
78,ESTADISTICA I,4,CIENP,17,SI,58,165,5,322,"4,69",F,III,PTWF
79,PROBABILIDAD,"4,5",INAM,17,NO,56,164,5,255,"3,8",F,II,PCWF
80,PROBABILIDAD,"3,5",INCV,18,SI,77,180,5,302,"3,5",M,VII,PTWF
81,PROBABILIDAD,4,INCV,18,SI,62,170,5,305,"3,9",M,I,PTWF
82,PROBABILIDAD,"4,5",INCV,18,NO,83,180,5,333,"3,8",M,II,PTWF
83,PROBABILIDAD,"4,5",INCV,18,SI,77,170,4,280,"3,84",M,III,PCWF
84,PROBABILIDAD,"4,5",INMC,17,SI,56,168,4,369,"4,5",F,III,PCWF
85,ESTADISTICA I,"4,5",COMS,18,SI,50,164,5,280,"4,4",F,IV,PTWF
86,ESTADISTICA I,"3,5",COMS,19,SI,51,175,4,260,"3,83",F,I,PCWF
87,ESTADISTICA I,4,DERH,18,SI,56,168,5,313,"4,3",F,III,PTWF
88,ESTADISTICA I,4,DERH,19,NO,62,165,5,253,"3,61",F,I,TBDT
89,ESTADISTICA I,4,PSIC,18,SI,49,160,5,340,"4,4",F,VI,PCWF
90,ESTADISTICA I,2,PSIC,19,SI,70,171,5,289,"3,3",M,III,CYWF
91,ESTADISTICA I,"3,5",CIENP,19,SI,77,176,5,297,"4,2",M,III,PCWF
92,ESTADISTICA I,4,CIENP,18,SI,65,172,4,278,"4,44",M,I,PCWF
93,ESTADISTICA I,5,COMS,18,SI,44,162,5,300,"4,4",F,III,PCWF
94,ESTADISTICA I,"2,5",PSIC,19,SI,48,158,4,292,"3,7",F,I,PTWF
95,ESTADISTICA I,2,DERH,20,SI,54,170,4,369,"3,6",M,I,PTWF
96,ESTADISTICA I,4,PSIC,20,SI,89,165,3,298,"4,69",M,V,PTWF
97,ESTADISTICA I,"3,5",COMS,17,SI,40,151,4,323,"3,9",F,II,PTWF
98,ESTADISTICA I,4,COMS,19,SI,65,169,5,204,"4,08",F,II,PCWF
99,ESTADISTICA I,5,CIENP,18,SI,57,160,5,318,"4,49",F,III,PCWF
100,ESTADISTICA I,"3,5",DERH,20,NO,72,172,4,205,35,F,I,PTWF
101,ESTADISTICA I,4,COMS,18,SI,97,185,5,290,"3,9",M,III,PTDT
102,ESTADISTICA I,"4,5",COMS,19,SI,57,161,5,349,"4,53",F,III,PTWF
103,ESTADISTICA I,4,COMS,17,SI,65,167,5,337,"4,1",F,IV,PCDT
104,ESTADISTICA I,"1,5",COMS,22,SI,61,161,4,275,"3,6",F,IV,PTWF
105,ESTADISTICA I,"4,5",PSIC,18,SI,56,168,5,372,"4,57",F,II,PCWF
106,ESTADISTICA I,5,COMS,18,SI,59,166,5,379,"4,7",F,IV,PCWF
107,ESTADISTICA I,"3,5",COMS,20,SI,54,155,5,255,"3,77",F,III,PTWF
108,ESTADISTICA I,"2,5",PSIC,20,NO,80,172,4,242,"3,6",F,I,PCDT
109,ESTADISTICA I,"3,5",PSIC,18,NO,47,162,5,229,"3,72",F,I,CYDT
110,ESTADISTICA I,"1,5",PSIC,27,SI,95,153,4,255,"3,38",F,III,CYDT
111,ESTADISTICA I,"1,5",COMS,19,SI,61,156,5,238,"3,5",F,III,PTWF
112,ESTADISTICA I,"3,5",COMS,19,SI,66,110,4,255,40,M,III,PCWF
113,ESTADISTICA I,"4,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PTWF
114,ESTADISTICA I,4,PSIC,18,NO,47,155,5,312,"4,39",F,V,PCWF
115,ESTADISTICA I,"2,5",PSIC,21,SI,70,185,3,356,"3,2",M,II,PCWF
116,ESTADISTICA I,"3,5",PSIC,18,SI,60,163,5,310,"3,9",F,III,PTWF
117,ESTADISTICA I,"3,5",PSIC,18,SI,60,180,3,346,"3,9",M,IV,PCWF
118,ESTADISTICA I,"2,5",COMS,21,NO,45,172,5,221,"3,7",F,II,CYWF
119,ESTADISTICA I,3,COMS,20,NO,50,160,4,332,"3,5",F,II,CYDT
120,ESTADISTICA I,"3,5",DERH,21,NO,57,160,4,293,"3,5",F,III,PTWF

## **b. Accediendo al atributo shape, el cual me muestra la cantidad de filas y columnas**

In [ ]:
# **b. Accediendo al atributo shape, el cual me muestra la cantidad de filas y columnas**
df_datos.shape

(121, 13)

## **c. El Atributo index muestra la misma información**

In [ ]:
# **c. El Atributo index muestra la misma información**
df_datos.index

RangeIndex(start=0, stop=121, step=1)

## **d. El Atributo _columns_ muestra el nombre de las variables**

In [ ]:
## **d. El Atributo -columns- muestra el nombre de las variables**
df_datos.columns

Index(['CURSO', 'DEFINITIVA', 'PROGRAMA', 'EDAD', 'URBANO', 'PESO', 'ESTATURA',
       'SATISFACC', 'SABER 11', 'PROMEDIO', 'SEXO', 'ESTRATO', 'Herramientas'],
      dtype='object')

## **e. El Atributo _dtypes_ muestra el tipo de las  variables**
### **Algunas variables numéricas aparecen como categoricas, dado que les aparece ',' en lugar de '.'**

In [ ]:
## **e. El Atributo _dtypes_ muestra el tipo de las  variables**
### **Algunas variables numéricas aparecen como categoricas, dado que les aparece ',' en lugar de '.'**
df_datos.dtypes

CURSO           object
DEFINITIVA      object
PROGRAMA        object
EDAD             int64
URBANO          object
PESO             int64
ESTATURA         int64
SATISFACC        int64
SABER 11         int64
PROMEDIO        object
SEXO            object
ESTRATO         object
Herramientas    object
dtype: object

#**38. Métodos usados para DataFrame**

## **a. El Método _info()_ muestra el tipo de las  variables en un DataFrame**
### **Algunas variables numéricas aparecen como categoricas, dado que les aparece ',' en lugar de '.'**

In [ ]:
## **a. El Método _info()_ muestra el tipo de las  variables en un DataFrame**
### **Algunas variables numéricas aparecen como categoricas, dado que les aparece ',' en lugar de '.'**
df_datos.info() # La variable DEFINITIVA aparece como cadena porque usa (,)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CURSO         121 non-null    object
 1   DEFINITIVA    121 non-null    object
 2   PROGRAMA      121 non-null    object
 3   EDAD          121 non-null    int64
 4   URBANO        121 non-null    object
 5   PESO          121 non-null    int64
 6   ESTATURA      121 non-null    int64
 7   SATISFACC     121 non-null    int64
 8   SABER 11      121 non-null    int64
 9   PROMEDIO      121 non-null    object
 10  SEXO          121 non-null    object
 11  ESTRATO       120 non-null    object
 12  Herramientas  121 non-null    object
dtypes: int64(5), object(8)
memory usage: 12.4+ KB

## **b. El Método _describe()_ muestra los estadisticos  concalculado las  variables en un DataFrame**
### **Mostrando analisis descriptivos de la información del DataFrame**

In [ ]:
## **b. El Método _describe()_ muestra los estadisticos  concalculado las  variables en un DataFrame**
### **Mostrando analisis descriptivos de la información del DataFrame**
df_datos.describe() # No aparece la variable DEFINITIVA

             EDAD        PESO    ESTATURA  SATISFACC    SABER 11
count  121.000000  121.000000  121.000000  121.00000  121.000000
mean    18.553719   63.239669  167.933884    4.53719  305.429752
std      1.653030   12.935755   12.369812    0.63300   43.059228
min     16.000000   37.000000  100.000000    3.00000  204.000000
25%     18.000000   55.000000  163.000000    4.00000  275.000000
50%     18.000000   61.000000  169.000000    5.00000  305.000000
75%     19.000000   73.000000  175.000000    5.00000  341.000000
max     27.000000   97.000000  192.000000    5.00000  380.000000

## **c. El Método _str.replace()_ permite reemplazar en las variables aquellas que aparecen con comas**
### **Cambiar la coma (,) por punto (.)**

In [ ]:
## **c. El Método _str.replace()_ permite reemplazar (.) en las variables aquellas que aparecen con comas (,)**
### **Cambiar la coma (,) por punto (.)**
df_datos["DEFINITIVA"]=df_datos["DEFINITIVA"].str.replace(",",".")
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].str.replace(",",".")
df_datos.head()

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,4.3,COMS,18,SI,55,164,4,350,4.26,F,II,PTWF
1,ESTADISTICA I,3.1,COMS,19,SI,65,165,5,328,4.11,F,I,CYDT
2,ESTADISTICA I,4.2,DERH,25,NO,56,170,5,285,3.7,M,I,CYDT
3,ESTADISTICA I,3.6,DERH,23,SI,65,170,5,280,4.1,F,II,PCWF
4,ESTADISTICA I,3.9,PSIC,19,SI,50,169,5,319,4,F,II,CYWF

## **d. Revisamos nuevamente con _info()_ Aun la variable DEFINITIVA  y PROMEDIO aparecen como OBJECT**

In [ ]:
## **d. Revisamos nuevamente con _info()_ Aun la variable DEFINITIVA  y PROMEDIO aparecen como OBJECT
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CURSO         121 non-null    object
 1   DEFINITIVA    121 non-null    object
 2   PROGRAMA      121 non-null    object
 3   EDAD          121 non-null    int64
 4   URBANO        121 non-null    object
 5   PESO          121 non-null    int64
 6   ESTATURA      121 non-null    int64
 7   SATISFACC     121 non-null    int64
 8   SABER 11      121 non-null    int64
 9   PROMEDIO      121 non-null    object
 10  SEXO          121 non-null    object
 11  ESTRATO       120 non-null    object
 12  Herramientas  121 non-null    object
dtypes: int64(5), object(8)
memory usage: 12.4+ KB

## **e. Mostrando analisis descriptivos de la información del DataFrame**

In [ ]:
## **e. Mostrando analisis descriptivos de la información del DataFrame**
df_datos.describe()

             EDAD        PESO    ESTATURA  SATISFACC    SABER 11
count  121.000000  121.000000  121.000000  121.00000  121.000000
mean    18.553719   63.239669  167.933884    4.53719  305.429752
std      1.653030   12.935755   12.369812    0.63300   43.059228
min     16.000000   37.000000  100.000000    3.00000  204.000000
25%     18.000000   55.000000  163.000000    4.00000  275.000000
50%     18.000000   61.000000  169.000000    5.00000  305.000000
75%     19.000000   73.000000  175.000000    5.00000  341.000000
max     27.000000   97.000000  192.000000    5.00000  380.000000

#**39. Cambiando de OBJETO A NUMERICO en el DataFrame**

## **a. Usando el método _astype()_ hacemos el cambio de tipo de variables**

In [ ]:
## **a. Usando el método _astype()_ hacemos el cambio de tipo de variables**
df_datos["DEFINITIVA"]=df_datos["DEFINITIVA"].astype(np.float64)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].astype(np.float64)

## **b. Revisamos nuevamente con _info()_ Aun la variable DEFINITIVA  y PROMEDIO aparecen como OBJECT**

In [ ]:
## **b. Revisamos nuevamente con _info()_ Aun la variable DEFINITIVA  y PROMEDIO aparecen como OBJECT
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CURSO         121 non-null    object
 1   DEFINITIVA    121 non-null    float64
 2   PROGRAMA      121 non-null    object
 3   EDAD          121 non-null    int64
 4   URBANO        121 non-null    object
 5   PESO          121 non-null    int64
 6   ESTATURA      121 non-null    int64
 7   SATISFACC     121 non-null    int64
 8   SABER 11      121 non-null    int64
 9   PROMEDIO      121 non-null    float64
 10  SEXO          121 non-null    object
 11  ESTRATO       120 non-null    object
 12  Herramientas  121 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 12.4+ KB

## **c. Mostrando analisis descriptivos de la información del DataFrame**
### _Al parecer hay algunos datos herrados en la Variable PROMEDIO__

In [ ]:
## **c. Mostrando analisis descriptivos de la información del DataFrame**
df_datos.describe()

,DEFINITIVA,EDAD,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO
count,121.000000,121.000000,121.000000,121.000000,121.00000,121.000000,121.000000
mean,3.773554,18.553719,63.239669,167.933884,4.53719,305.429752,8.231901
std,0.863980,1.653030,12.935755,12.369812,0.63300,43.059228,34.015054
min,1.100000,16.000000,37.000000,100.000000,3.00000,204.000000,3.200000
25%,3.500000,18.000000,55.000000,163.000000,4.00000,275.000000,3.800000
50%,4.000000,18.000000,61.000000,169.000000,5.00000,305.000000,4.010000
75%,4.500000,19.000000,73.000000,175.000000,5.00000,341.000000,4.300000
max,5.000000,27.000000,97.000000,192.000000,5.00000,380.000000,373.000000

## **d. Con la función _len()_ tambien podemos explorar el tamaño del Data Frame**

In [ ]:
## **d. Con la función _len()_ tambien podemos explorar el tamaño del Data Frame**
len(df_datos) # numero de filas

121

## **e. La función _max_ y el atributo _index_ podemos visualizar el máximo en cada variable**

In [ ]:
## **e. La función _max_ y el atributo _index_ podemos visualizar el máximo en cada variable**
max(df_datos.index)

120

## **f. La función _min_ y el atributo _index_ podemos visualizar el mínimo**

In [ ]:
## **f. La función _min_ y el atributo _index_ podemos visualizar el mínimo**
min(df_datos.index)

0

## **g. La función _type_  la clase del DataFrame**

In [ ]:
## **g. La función _type_  la clase del DataFrame**
type(df_datos)

pandas.core.frame.DataFrame

## **h. La función _round_  podemos redondear en el DataFrame**

In [ ]:
## **h. La función _round_  podemos redondear en el DataFrame**
round(df_datos,1)

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas
0,ESTADISTICA I,4.3,COMS,18,SI,55,164,4,350,4.3,F,II,PTWF
1,ESTADISTICA I,3.1,COMS,19,SI,65,165,5,328,4.1,F,I,CYDT
2,ESTADISTICA I,4.2,DERH,25,NO,56,170,5,285,3.7,M,I,CYDT
3,ESTADISTICA I,3.6,DERH,23,SI,65,170,5,280,4.1,F,II,PCWF
4,ESTADISTICA I,3.9,PSIC,19,SI,50,169,5,319,4.0,F,II,CYWF
5,ESTADISTICA I,1.1,PSIC,19,SI,68,165,4,318,3.7,M,III,PTWF
6,ESTADISTICA I,3.5,CIENP,19,SI,86,184,5,345,4.5,F,II,PTWF
7,ESTADISTICA I,4.2,CIENP,19,NO,53,163,5,257,3.7,M,I,PTWF
8,PROBABILIDAD,4.4,ININ,18,NO,56,158,5,298,3.8,F,II,PTDT
9,PROBABILIDAD,4.1,INMT,20,SI,72,179,4,353,3.9,M,III,PCWF
10,PROBABILIDAD,4.8,INNV,18,SI,64,175,4,354,4.7,M,III,PTWF
11,PROBABILIDAD,4.5,ININ,17,NO,75,177,4,242,4.7,F,I,PTDT
12,PROBABILIDAD,3.9,INQU,19,SI,61,158,4,329,3.8,F,II,CYDT
13,PROBABILIDAD,3.3,ININ,17,SI,57,164,5,354,3.8,M,II,PCWF
14,PROBABILIDAD,4.0,INMT,18,NO,50,168,5,265,4.3,M,I,CYDT
15,ESTADISTICA I,3.8,COMS,20,SI,87,174,5,290,3.8,M,VI,PTWF
16,ESTADISTICA I,3.5,COMS,16,SI,54,169,5,325,4.5,F,II,PTDT
17,ESTADISTICA I,4.2,DERH,18,SI,80,181,5,273,3.8,M,IV,TBDT
18,ESTADISTICA I,3.6,DERH,19,SI,60,182,5,333,4.0,M,II,PTWF
19,ESTADISTICA I,4.1,PSIC,18,SI,90,176,5,298,3.9,M,II,PCWF
20,ESTADISTICA I,2.5,PSIC,20,SI,50,157,5,310,3.9,F,II,PCWF
21,ESTADISTICA I,3.6,CIENP,19,SI,55,156,5,278,3.9,F,V,PTWF
22,ESTADISTICA I,4.5,CIENP,18,SI,74,183,5,365,4.3,M,II,PTWF
23,PROBABILIDAD,4.0,INST,18,NO,63,183,4,352,4.0,M,II,PCWF
24,PROBABILIDAD,5.0,INAM,17,SI,48,158,4,327,4.2,F,I,PCWF
25,ESTADISTICA I,3.6,DERH,18,SI,85,179,5,270,3.8,M,IV,PCWF
26,ESTADISTICA I,4.0,PSIC,20,SI,60,175,5,214,373.0,M,I,CYDT
27,ESTADISTICA I,3.0,PSIC,17,NO,61,155,5,275,37.0,F,NaN,PCWF
28,ESTADISTICA I,4.0,CIENP,18,SI,68,185,5,330,4.0,M,VI,CYDT
29,PROBABILIDAD,4.5,INMT,17,SI,85,175,5,357,3.8,M,II,PTWF
30,PROBABILIDAD,4.3,INBM,17,SI,45,155,5,356,4.1,F,V,PTWF
31,ESTADISTICA I,4.5,COMS,17,NO,60,162,4,230,3.8,F,II,PCWF
32,ESTADISTICA I,3.0,COMS,18,SI,65,169,5,300,3.8,M,II,PTWF
33,ESTADISTICA I,3.5,DERH,21,SI,62,100,5,210,3.9,F,II,CYWF
34,ESTADISTICA I,3.2,DERH,17,NO,60,170,5,313,4.1,M,II,PTDT
35,ESTADISTICA I,3.6,PSIC,18,SI,56,163,4,292,4.3,F,III,PTWF
36,ESTADISTICA I,4.0,PSIC,18,SI,75,190,4,365,4.0,M,I,PCWF
37,ESTADISTICA I,5.0,CIENP,19,SI,73,182,5,333,4.1,M,III,PTWF
38,ESTADISTICA I,3.8,CIENP,17,NO,73,175,4,342,4.3,M,I,PCWF
39,PROBABILIDAD,4.3,INMC,24,NO,90,176,5,240,3.7,M,II,TBWF
40,PROBABILIDAD,4.3,INMC,18,SI,47,167,4,311,4.2,M,III,PCDT
41,ESTADISTICA I,4.5,COMS,19,SI,50,165,3,316,3.9,F,II,PTWF
42,ESTADISTICA I,3.0,COMS,17,SI,70,173,5,355,4.0,M,III,PTWF
43,ESTADISTICA I,5.0,DERH,20,SI,63,160,4,273,4.0,F,I,PTWF
44,PROBABILIDAD,5.0,INCV,17,NO,37,148,5,230,3.9,F,I,PTWF
45,PROBABILIDAD,5.0,FINN,18,SI,58,165,5,273,4.2,F,II,PTWF
46,PROBABILIDAD,4.8,ININ,20,SI,73,163,5,263,3.7,F,II,PTWF
47,PROBABILIDAD,2.5,INMT,17,SI,64,180,4,358,3.9,M,II,CYWF
48,PROBABILIDAD,3.0,INNV,18,NO,80,175,5,289,3.8,M,II,PTWF
49,PROBABILIDAD,3.8,INMC,17,NO,70,170,5,269,4.0,M,I,PCDT
50,ESTADISTICA I,4.4,COMS,18,SI,60,165,5,380,4.7,F,IV,CYDT
51,ESTADISTICA I,2.5,COMS,18,SI,77,180,5,338,4.1,M,II,PTWF
52,ESTADISTICA I,4.2,DERH,17,NO,59,169,4,298,4.0,M,II,CYDT
53,ESTADISTICA I,3.7,DERH,17,SI,40,164,4,353,4.3,F,II,PCWF
54,ESTADISTICA I,4.0,PSIC,18,SI,49,163,5,297,42.6,F,IV,PTWF
55,ESTADISTICA I,2.0,PSIC,17,SI,60,164,3,289,4.1,F,II,PCWF
56,ESTADISTICA I,3.5,CIENP,17,NO,59,176,4,333,3.9,M,III,PTWF
57,ESTADISTICA I,4.2,CIENP,17,SI,62,168,4,298,4.1,F,I,PTWF
58,PROBABILIDAD,4.5,INMT,19,SI,74,171,3,370,4.3,M,II,PTWF
59,PROBABILIDAD,5.0,INMT,19,SI,64,174,5,352,4.2,M,III,PCWF
60,PROBABILIDAD,4.0,INST,22,SI,75,175,5,255,4.2,M,IV,PTWF
61,PROBABILIDAD,5.0,FINN,18,NO,51,154,5,368,4.5,F,II,PTWF
62,ESTADISTICA I,4.3,COMS,18,SI,37,178,4,270,3.6,M,II,CYDT
63,ESTADISTICA I,2.5,COMS,18,NO,75,183,5,328,4.2,M,I,PTDT
64,ESTADISTICA I,4.5,DERH,17,SI,45,140,4,341,4.0,M,I,PTWF
65,PROBABILIDAD,4.5,INMT,17,SI,60,170,5,341,4.6,M,I,PTWF
66,PROBABILIDAD,4.0,INMC,18,NO,60,171,3,364,4.3,M,III,PCWF
67,PROBABILIDAD,3.5,INMC,17,SI,90,185,5,300,3.8,M,III,PTWF
68,PROBABILIDAD,2.5,ECOM,18,SI,75,170,5,288,4.0,F,II,PTWF
69,PROBABILIDAD,5.0,FINN,19,NO,78,175,5,294,4.6,F,III,PTWF
70,PROBABILIDAD,4.5,INNV,17,NO,79,174,5,356,4.4,M,II,PTWF
71,ESTADISTICA I,4.5,COMS,18,SI,62,169,4,315,4.1,F,IV,PTWF
72,ESTADISTICA I,2.5,COMS,18,SI,80,180,5,361,4.5,M,II,PCWF
73,ESTADISTICA I,4.2,DERH,19,NO,45,158,4,283,4.0,F,I,PCWF
74,ESTADISTICA I,3.7,DERH,18,SI,50,170,4,300,4.2,M,III,PCWF
75,ESTADISTICA I,4.0,PSIC,18,SI,59,165,5,310,4.4,F,IV,PCDT
76,ESTADISTICA I,2.0,PSIC,18,SI,65,166,5,250,4.3,M,II,PTWF
77,ESTADISTICA I,3.5,CIENP,20,SI,73,192,3,356,3.8,M,III,PCWF
78,ESTADISTICA I,4.0,CIENP,17,SI,58,165,5,322,4.7,F,III,PTWF
79,PROBABILIDAD,4.5,INAM,17,NO,56,164,5,255,3.8,F,II,PCWF
80,PROBABILIDAD,3.5,INCV,18,SI,77,180,5,302,3.5,M,VII,PTWF
81,PROBABILIDAD,4.0,INCV,18,SI,62,170,5,305,3.9,M,I,PTWF
82,PROBABILIDAD,4.5,INCV,18,NO,83,180,5,333,3.8,M,II,PTWF
83,PROBABILIDAD,4.5,INCV,18,SI,77,170,4,280,3.8,M,III,PCWF
84,PROBABILIDAD,4.5,INMC,17,SI,56,168,4,369,4.5,F,III,PCWF
85,ESTADISTICA I,4.5,COMS,18,SI,50,164,5,280,4.4,F,IV,PTWF
86,ESTADISTICA I,3.5,COMS,19,SI,51,175,4,260,3.8,F,I,PCWF
87,ESTADISTICA I,4.0,DERH,18,SI,56,168,5,313,4.3,F,III,PTWF
88,ESTADISTICA I,4.0,DERH,19,NO,62,165,5,253,3.6,F,I,TBDT
89,ESTADISTICA I,4.0,PSIC,18,SI,49,160,5,340,4.4,F,VI,PCWF
90,ESTADISTICA I,2.0,PSIC,19,SI,70,171,5,289,3.3,M,III,CYWF
91,ESTADISTICA I,3.5,CIENP,19,SI,77,176,5,297,4.2,M,III,PCWF
92,ESTADISTICA I,4.0,CIENP,18,SI,65,172,4,278,4.4,M,I,PCWF
93,ESTADISTICA I,5.0,COMS,18,SI,44,162,5,300,4.4,F,III,PCWF
94,ESTADISTICA I,2.5,PSIC,19,SI,48,158,4,292,3.7,F,I,PTWF
95,ESTADISTICA I,2.0,DERH,20,SI,54,170,4,369,3.6,M,I,PTWF
96,ESTADISTICA I,4.0,PSIC,20,SI,89,165,3,298,4.7,M,V,PTWF
97,ESTADISTICA I,3.5,COMS,17,SI,40,151,4,323,3.9,F,II,PTWF
98,ESTADISTICA I,4.0,COMS,19,SI,65,169,5,204,4.1,F,II,PCWF
99,ESTADISTICA I,5.0,CIENP,18,SI,57,160,5,318,4.5,F,III,PCWF
100,ESTADISTICA I,3.5,DERH,20,NO,72,172,4,205,35.0,F,I,PTWF
101,ESTADISTICA I,4.0,COMS,18,SI,97,185,5,290,3.9,M,III,PTDT
102,ESTADISTICA I,4.5,COMS,19,SI,57,161,5,349,4.5,F,III,PTWF
103,ESTADISTICA I,4.0,COMS,17,SI,65,167,5,337,4.1,F,IV,PCDT
104,ESTADISTICA I,1.5,COMS,22,SI,61,161,4,275,3.6,F,IV,PTWF
105,ESTADISTICA I,4.5,PSIC,18,SI,56,168,5,372,4.6,F,II,PCWF
106,ESTADISTICA I,5.0,COMS,18,SI,59,166,5,379,4.7,F,IV,PCWF
107,ESTADISTICA I,3.5,COMS,20,SI,54,155,5,255,3.8,F,III,PTWF
108,ESTADISTICA I,2.5,PSIC,20,NO,80,172,4,242,3.6,F,I,PCDT
109,ESTADISTICA I,3.5,PSIC,18,NO,47,162,5,229,3.7,F,I,CYDT
110,ESTADISTICA I,1.5,PSIC,27,SI,95,153,4,255,3.4,F,III,CYDT
111,ESTADISTICA I,1.5,COMS,19,SI,61,156,5,238,3.5,F,III,PTWF
112,ESTADISTICA I,3.5,COMS,19,SI,66,110,4,255,40.0,M,III,PCWF
113,ESTADISTICA I,4.5,PSIC,18,SI,60,180,3,346,3.9,M,IV,PTWF
114,ESTADISTICA I,4.0,PSIC,18,NO,47,155,5,312,4.4,F,V,PCWF
115,ESTADISTICA I,2.5,PSIC,21,SI,70,185,3,356,3.2,M,II,PCWF
116,ESTADISTICA I,3.5,PSIC,18,SI,60,163,5,310,3.9,F,III,PTWF
117,ESTADISTICA I,3.5,PSIC,18,SI,60,180,3,346,3.9,M,IV,PCWF
118,ESTADISTICA I,2.5,COMS,21,NO,45,172,5,221,3.7,F,II,CYWF
119,ESTADISTICA I,3.0,COMS,20,NO,50,160,4,332,3.5,F,II,CYDT
120,ESTADISTICA I,3.5,DERH,21,NO,57,160,4,293,3.5,F,III,PTWF

#**40. Seleccionar una columna en el DataFrame para analizar los problemas**

In [ ]:
## **a. Revisando la columna PROMEDIO**
df_datos["PROMEDIO"]

0        4.26
1        4.11
2        3.70
3        4.10
4        4.00
5        3.70
6        4.48
7        3.70
8        3.80
9        3.90
10       4.69
11       4.69
12       3.77
13       3.77
14       4.30
15       3.80
16       4.48
17       3.79
18       4.00
19       3.90
20       3.90
21       3.86
22       4.31
23       4.02
24       4.22
25       3.82
26     373.00
27      37.00
28       4.01
29       3.78
30       4.12
31       3.80
32       3.81
33       3.90
34       4.10
35       4.30
36       4.03
37       4.08
38       4.26
39       3.70
40       4.20
41       3.90
42       4.03
43       4.00
44       3.87
45       4.22
46       3.73
47       3.88
48       3.80
49       4.00
50       4.68
51       4.10
52       4.01
53       4.33
54      42.60
55       4.10
56       3.90
57       4.10
58       4.30
59       4.20
60       4.20
61       4.46
62       3.60
63       4.20
64       4.01
65       4.57
66       4.30
67       3.79
68       4.01
69       4.60
70       4.40
71       4.10
72       4.50
73       3.95
74       4.20
75       4.40
76       4.30
77       3.83
78       4.69
79       3.80
80       3.50
81       3.90
82       3.80
83       3.84
84       4.50
85       4.40
86       3.83
87       4.30
88       3.61
89       4.40
90       3.30
91       4.20
92       4.44
93       4.40
94       3.70
95       3.60
96       4.69
97       3.90
98       4.08
99       4.49
100     35.00
101      3.90
102      4.53
103      4.10
104      3.60
105      4.57
106      4.70
107      3.77
108      3.60
109      3.72
110      3.38
111      3.50
112     40.00
113      3.90
114      4.39
115      3.20
116      3.90
117      3.90
118      3.70
119      3.50
120      3.50
Name: PROMEDIO, dtype: float64

## **b. La Variable PROMEDIO tiene errores en la entrada**
|||
|:--:|:--:|
|26|     373.00|
|27|      37.00|
|54|      42.60|
|100|     35.00|
|112|     40.00|

## **c. Realizamos las correcciones pertinenetes en la Variable PROMEDIO**

In [ ]:
## **c. Realizamos las correcciones pertinenetes en la Variable PROMEDIO**
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(40.00,4.0)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(35.00,3.5)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(42.00,4.2)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(37.00,3.7)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(373.00,3.7)
df_datos["PROMEDIO"]=df_datos["PROMEDIO"].replace(42.60,4.3)
df_datos["PROMEDIO"]

0      4.26
1      4.11
2      3.70
3      4.10
4      4.00
5      3.70
6      4.48
7      3.70
8      3.80
9      3.90
10     4.69
11     4.69
12     3.77
13     3.77
14     4.30
15     3.80
16     4.48
17     3.79
18     4.00
19     3.90
20     3.90
21     3.86
22     4.31
23     4.02
24     4.22
25     3.82
26     3.70
27     3.70
28     4.01
29     3.78
30     4.12
31     3.80
32     3.81
33     3.90
34     4.10
35     4.30
36     4.03
37     4.08
38     4.26
39     3.70
40     4.20
41     3.90
42     4.03
43     4.00
44     3.87
45     4.22
46     3.73
47     3.88
48     3.80
49     4.00
50     4.68
51     4.10
52     4.01
53     4.33
54     4.30
55     4.10
56     3.90
57     4.10
58     4.30
59     4.20
60     4.20
61     4.46
62     3.60
63     4.20
64     4.01
65     4.57
66     4.30
67     3.79
68     4.01
69     4.60
70     4.40
71     4.10
72     4.50
73     3.95
74     4.20
75     4.40
76     4.30
77     3.83
78     4.69
79     3.80
80     3.50
81     3.90
82     3.80
83     3.84
84     4.50
85     4.40
86     3.83
87     4.30
88     3.61
89     4.40
90     3.30
91     4.20
92     4.44
93     4.40
94     3.70
95     3.60
96     4.69
97     3.90
98     4.08
99     4.49
100    3.50
101    3.90
102    4.53
103    4.10
104    3.60
105    4.57
106    4.70
107    3.77
108    3.60
109    3.72
110    3.38
111    3.50
112    4.00
113    3.90
114    4.39
115    3.20
116    3.90
117    3.90
118    3.70
119    3.50
120    3.50
Name: PROMEDIO, dtype: float64

## **d. Nuevamente redondeamos y nos concentramos en la variable PROMEDIO**

In [ ]:
## **d. Nuevamente redondeamos y nos concentramos en la variable PROMEDIO**
round(df_datos["PROMEDIO"],1)

0      4.3
1      4.1
2      3.7
3      4.1
4      4.0
5      3.7
6      4.5
7      3.7
8      3.8
9      3.9
10     4.7
11     4.7
12     3.8
13     3.8
14     4.3
15     3.8
16     4.5
17     3.8
18     4.0
19     3.9
20     3.9
21     3.9
22     4.3
23     4.0
24     4.2
25     3.8
26     3.7
27     3.7
28     4.0
29     3.8
30     4.1
31     3.8
32     3.8
33     3.9
34     4.1
35     4.3
36     4.0
37     4.1
38     4.3
39     3.7
40     4.2
41     3.9
42     4.0
43     4.0
44     3.9
45     4.2
46     3.7
47     3.9
48     3.8
49     4.0
50     4.7
51     4.1
52     4.0
53     4.3
54     4.3
55     4.1
56     3.9
57     4.1
58     4.3
59     4.2
60     4.2
61     4.5
62     3.6
63     4.2
64     4.0
65     4.6
66     4.3
67     3.8
68     4.0
69     4.6
70     4.4
71     4.1
72     4.5
73     4.0
74     4.2
75     4.4
76     4.3
77     3.8
78     4.7
79     3.8
80     3.5
81     3.9
82     3.8
83     3.8
84     4.5
85     4.4
86     3.8
87     4.3
88     3.6
89     4.4
90     3.3
91     4.2
92     4.4
93     4.4
94     3.7
95     3.6
96     4.7
97     3.9
98     4.1
99     4.5
100    3.5
101    3.9
102    4.5
103    4.1
104    3.6
105    4.6
106    4.7
107    3.8
108    3.6
109    3.7
110    3.4
111    3.5
112    4.0
113    3.9
114    4.4
115    3.2
116    3.9
117    3.9
118    3.7
119    3.5
120    3.5
Name: PROMEDIO, dtype: float64

#**e. Seleccionar dos o mas columnas en el DataFrame**

In [ ]:
#**e. Seleccionar dos o mas columnas en el DataFrame**
df_datos[["PESO", "ESTATURA"]].head()

   PESO  ESTATURA
0    55       164
1    65       165
2    56       170
3    65       170
4    50       169

#**f. Seleccionar dos o mas columnas en el DataFrame**

In [ ]:
#**f. Seleccionar dos o mas columnas en el DataFrame**
df_datos[["SEXO", "PESO", "ESTATURA"]].head()

  SEXO  PESO  ESTATURA
0    F    55       164
1    F    65       165
2    M    56       170
3    F    65       170
4    F    50       169

# **41. Exportar dataframes limpios**

In [ ]:
# **41. Exportar dataframes limpios**
df_datos.to_csv('df_datos_LIMPIOS.csv',index=False)